import { Investment } from '../types';

/**
 * Loads the Google Identity Services script dynamically
 */
export function loadGisScript(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (document.getElementById('google-gis-sdk')) {
      resolve();
      return;
    }
    const script = document.createElement('script');
    script.src = 'https://accounts.google.com/gsi/client';
    script.id = 'google-gis-sdk';
    script.async = true;
    script.defer = true;
    script.onload = () => resolve();
    script.onerror = () => reject(new Error('Failed to load Google GIS SDK'));
    document.head.appendChild(script);
  });
}

/**
 * Initialize Google Identity Services OAuth Token Client and request access token
 */
export function requestGoogleCalendarToken(clientId: string): Promise<string> {
  return new Promise((resolve, reject) => {
    try {
      // @ts-ignore - google is injected on window by accounts.google.com/gsi/client
      if (typeof google === 'undefined' || !google.accounts?.oauth2) {
        reject(new Error('Google GIS SDK not loaded or initialized yet'));
        return;
      }

      // @ts-ignore
      const client = google.accounts.oauth2.initTokenClient({
        client_id: clientId,
        scope: 'https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/calendar.events',
        callback: (response: any) => {
          if (response.error) {
            reject(new Error(`OAuth Error: ${response.error_description || response.error}`));
            return;
          }
          if (response.access_token) {
            resolve(response.access_token);
          } else {
            reject(new Error('No access token returned from Google authentication'));
          }
        },
      });

      client.requestAccessToken({ prompt: 'consent' });
    } catch (e) {
      reject(e);
    }
  });
}

/**
 * Helper to call Google Calendar REST API
 */
async function callCalendarApi(
  endpoint: string,
  method: string,
  token: string,
  body?: any
): Promise<any> {
  const headers = new Headers();
  headers.append('Authorization', `Bearer ${token}`);
  headers.append('Content-Type', 'application/json');

  const options: RequestInit = {
    method,
    headers,
  };

  if (body) {
    options.body = JSON.stringify(body);
  }

  const response = await fetch(`https://www.googleapis.com/calendar/v3${endpoint}`, options);
  
  if (!response.ok) {
    const errText = await response.text();
    let parsedErr;
    try {
      parsedErr = JSON.parse(errText);
    } catch {
      parsedErr = { error: { message: errText } };
    }
    throw new Error(parsedErr?.error?.message || `Google Calendar API error (${response.status})`);
  }

  if (response.status === 204) {
    return true; // No Content
  }

  return response.json();
}

/**
 * Sync (Create or Update) Maturity Event in Google Calendar
 */
export async function syncMaturityEvent(
  investment: Investment,
  token: string
): Promise<string> {
  if (!investment.maturityDate) {
    throw new Error('Investment does not have a maturity date');
  }

  const formattedValue = new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
  }).format(investment.principal);

  const eventBody = {
    summary: `💸 Maturity: ${investment.type} - ${investment.name}`,
    description: `Investment Maturity Alert!
-----------------------------
Asset Type: ${investment.type}
Investment Name: ${investment.name}
Invested Amount: ${formattedValue}
Interest/Returns Rate: ${investment.rate}%
Start Date: ${investment.startDate}
Maturity Date: ${investment.maturityDate}

Notes:
${investment.notes || 'No added notes'}

Automatic notification generated by Investment Tracker app.`,
    start: {
      date: investment.maturityDate, // All-day event
    },
    end: {
      // For all-day events, 'end' date is exclusive. To make it show on maturityDate, end is next day.
      date: getNextDayString(investment.maturityDate),
    },
    colorId: '4', // Blue/green tone in Google Calendar
    reminders: {
      useDefault: false,
      overrides: [
        { method: 'popup', minutes: 1440 }, // 1 day before
        { method: 'email', minutes: 1440 }, // 1 day before
      ],
    },
  };

  if (investment.googleEventId) {
    try {
      // Attempt to update existing event
      const updatedEvent = await callCalendarApi(
        `/calendars/primary/events/${investment.googleEventId}`,
        'PUT',
        token,
        eventBody
      );
      return updatedEvent.id;
    } catch {
      // If updating fails (maybe deleted on calendar), create a new one
      const newEvent = await callCalendarApi(
        '/calendars/primary/events',
        'POST',
        token,
        eventBody
      );
      return newEvent.id;
    }
  } else {
    // Create new event
    const newEvent = await callCalendarApi(
      '/calendars/primary/events',
      'POST',
      token,
      eventBody
    );
    return newEvent.id;
  }
}

/**
 * Sync (Create or Update) Review Event in Google Calendar
 */
export async function syncReviewEvent(
  investment: Investment,
  token: string
): Promise<string> {
  if (!investment.reviewDate) {
    throw new Error('Investment does not have a review date');
  }

  const formattedValue = new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
  }).format(investment.principal);

  const eventBody = {
    summary: `🔍 Review: ${investment.type} - ${investment.name}`,
    description: `Investment Check-up & Review Scheduled!
-----------------------------
Asset Type: ${investment.type}
Investment Name: ${investment.name}
Invested Amount: ${formattedValue}
Current Rate: ${investment.rate}%
Start Date: ${investment.startDate}
Maturity Date: ${investment.maturityDate || 'Not specified'}

Notes associated:
${investment.notes || 'No added notes'}

Keep your portfolio optimized! Generated by Investment Tracker.`,
    start: {
      date: investment.reviewDate,
    },
    end: {
      date: getNextDayString(investment.reviewDate),
    },
    colorId: '5', // Yellow/banana tone
    reminders: {
      useDefault: false,
      overrides: [
        { method: 'popup', minutes: 540 }, // 9 hours before (morning)
      ],
    },
  };

  if (investment.reviewGoogleEventId) {
    try {
      const updatedEvent = await callCalendarApi(
        `/calendars/primary/events/${investment.reviewGoogleEventId}`,
        'PUT',
        token,
        eventBody
      );
      return updatedEvent.id;
    } catch {
      const newEvent = await callCalendarApi(
        '/calendars/primary/events',
        'POST',
        token,
        eventBody
      );
      return newEvent.id;
    }
  } else {
    const newEvent = await callCalendarApi(
      '/calendars/primary/events',
      'POST',
      token,
      eventBody
    );
    return newEvent.id;
  }
}

/**
 * Delete event from Google Calendar
 */
export async function deleteCalendarEvent(eventId: string, token: string): Promise<boolean> {
  try {
    await callCalendarApi(`/calendars/primary/events/${eventId}`, 'DELETE', token);
    return true;
  } catch (error) {
    console.warn('Could not delete calendar event:', error);
    return false;
  }
}

/**
 * Utility: Gets YYYY-MM-DD of the day after specified YYYY-MM-DD
 */
function getNextDayString(dateStr: string): string {
  const parts = dateStr.split('-');
  if (parts.length !== 3) return dateStr;
  const year = parseInt(parts[0], 10);
  const month = parseInt(parts[1], 10) - 1;
  const day = parseInt(parts[2], 10);

  const d = new Date(year, month, day);
  d.setDate(d.getDate() + 1);

  const y4 = d.getFullYear();
  const m2 = String(d.getMonth() + 1).padStart(2, '0');
  const d2 = String(d.getDate()).padStart(2, '0');

  return `${y4}-${m2}-${d2}`;
}
